### ISSUE TITLE
Crosswalk issue

### ISSUE THREAD

**Issue by bwasnie1** [cowbell/cordova-plugin-geofence#18]
I've added crosswalk to my cordova app to boost performance. But this plugin seems to be incompatible with crosswalk. I always get these errors:
![crosswalk](https://cloud.githubusercontent.com/assets/3907591/6283745/b207f4ce-b8e8-11e4-9262-282d3015bfd1.PNG)

How to fix this?

**Comment by tsubik** [comment]
I've never tried crosswalk. It could be interesting though. I am gonna take a look if I find some time.

**Comment by PaperMonster** [comment]
I've had this problem few days ago. In my case I've installed few plugins that bundled android-support-v4 library so Gradle considered those as duplicates and refused to build. My temporary solution are either:

1. Build the project using ANT instead by using the command `ANDROID_BUILD=ant cordova run android`. It seems that ANT allows duplicate JARs.
2. Remove platforms/android/libs/android-support-v4.jar from the project and try Gradle build again.

I prefer solution 2 as Gradle build make APK smaller. I guess this is not plugin-specific issue but Gradle's (which has become default Android builder since Cordova 4.0) default behavior.
Hope this helps.

**Comment by bwasnie1** [comment]
Thanks, that helped! Good job
