### ISSUE TITLE
Cordova build on iOS fails

### ISSUE THREAD

**Issue by gleerman** [cowbell/cordova-plugin-geofence#21]
Hi,

Perhaps somewhat related to [this issue](https://github.com/cowbell/cordova-plugin-geofence/issues/16), since I have to configure the IPHONEOS_DEPLOYMENT_TARGET manually (cordova version 4.2.0).

Anyway, after I manually set the parameter, the build is still failing. My impression is that some dependencies are missing for SQLITE. I did not install anything else than this plugin, but if I understood the documentation correctly it should work out of the box.

![screen shot 2015-03-03 at 11 16 44](https://cloud.githubusercontent.com/assets/5098787/6460352/d785d05c-c196-11e4-9755-f17df79da92f.png)

What am I missing? If some dependencies are needed, could this be added to the documentation?
Perhaps this should be set up as part of the hooked script, which is not executed correctly. How can I fix that?

Thanks

**Comment by shmay** [comment]
Ran into a similar problem.  Oddly, removing/adding the ios platform got it working:

```
cordova platform remove ios
cordova platform add ios
```

**Comment by tsubik** [comment]
I think it might be an issue with cordova itself. I also had some problems with xcode project file but only after the first `cordova platform add ios` when I hadn't had any plugins installed. I believe that problem may be related to the fact that xcode project is also modified by cordova library in the same time. Let me check it.

**Comment by tsubik** [comment]
Ok. I've found where my original problem was. Even if I removed `add_swift_support.js` hook I still have strange problem that all plugins were not installed correctly. It turns out that files from only one plugin were successfully added to xcode project file, and that plugin was a random one. I am using some kind of `install_plugins` hook after platform is added and the problem occurred because plugins were installed asynchronously. I've changed to [synchronous execution](https://github.com/cowbell/ionic-geofence/blob/master/hooks/after_platform_add/010_install_plugins.js#L17) and everything is fine so far.
