### ISSUE TITLE
Incorrect dependency IDs and Android permission declarations

### ISSUE THREAD

**Issue by ericvangeem** [cowbell/cordova-plugin-geofence#65]
In one of your recent commits of the plugin.xml file, you changed the ID of Android specific libraries to invalid IDs that do not exist in the plugin repository. Also, there is an issue with the declared `uses-permission` tags not being included in the compiled AndroidManifest.xml, resulting in the plugin not being able to use the Android location services as well as the "boot completed" broadcast.

**Comment by tsubik** [comment]
Hey @ericvangeem I am using new plugin ids due to [moving plugins from registry to npm](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html). However I have noticed a bug in Cordova-CLI when you are mixing old ids with new ones in your config.xml. It won't install all plugins correctly after `cordova platform add`. Installing plugin via `cordova plugin add cordova-plugin-geofence` works fine though. Take a look [here](https://issues.apache.org/jira/browse/CB-9138).

**Comment by tsubik** [comment]
Closed due inactivity.
