### ISSUE TITLE
Uncaught TypeError: Promise is not a function

### ISSUE THREAD

**Issue by PaperMonster** [cowbell/cordova-plugin-geofence#75]
After updating plugin to version 4.1.0, the plugin stopped working. Any javascript function call caused the error as following:
````
"Uncaught TypeError: Promise is not a function", source: file:///android_asset/www/plugins/cordova-plugin-geofence/www/geofence.js (119)
````
Changing the line 119 in geofence.js from `new Promise` to `new window.Promise` fixed the problem.
Tested with Nexus 5.

**Comment by andiCR** [comment]
I had the same issue, at least with Android. I ended up forking the plugin and removing the Promise dependency. It really makes no sense to have this other than syntactic sugar, but we could have a way more stable plugin without having this dependency, and working very well. The premise is to replace the calls to execPromise with just pure exec and then just use the calls as function parameters, and not  with the promise's .then().
So instead of
```javascript
window.geofence.getWatched().then(function (geofencesJson) {
  var geofences = JSON.parse(geofencesJson);
});
```
we would use

```javascript
window.geofence.getWatched(function(geofencesJson){ 
    var geofences = JSON.parse(geofencesJson);
});
```
