### ISSUE TITLE
Not seeing local notifications

### ISSUE THREAD

**Issue by garrettlangley** [cowbell/cordova-plugin-geofence#87]
Running sim ios9, I see console logs being thrown and if the app is open a toast notifcation is visible, but I am unable to see any local notifications. Any tips?

Thanks

**Comment by freinbichler** [comment]
I am having the same problem. Will there be an updated version for iOS 9 or do I need to look into it by myself? I need this functionality for a project I am currently working on.

**Comment by tsubik** [comment]
Support for iOS9 merged into master #82. Take a look and see if it works now.

**Comment by freinbichler** [comment]
I tried @Mojo90's [fork](https://github.com/Mojo90/cordova-plugin-geofence) yesterday, which did not work. But I will try again with the merged pull request.

**Comment by freinbichler** [comment]
I just tried the latest version, console log says "creating notification", but no notification appears. It doesn't matter if the app is open or closed. iPhone 6s on iOS 9.0.2.

**Comment by Mojo90** [comment]
Sorry @freinbichler  I didn't test Local Notifications for this Plugin cause I am using Katzers Local Notification Plugin as I do need update some things before firing local Push... (https://github.com/katzer/cordova-plugin-local-notifications)

**Comment by derek1988ec** [comment]
Hello @Mojo90 , the local notification works fine for me in iOS but I've encountered an error when I open the notification:

SyntaxError: Unexpected identifier 'Domain'. Expected ')' to end a argument list.

I've looked everywhere in my code and I don't see any syntax error and it only happens when I open the app from the notification drawer, else it works fine. Any idea what caused this?

**Comment by garrettlangley** [comment]
:+1:

**Comment by garrettlangley** [comment]
@derek1988ec I am seeing a similar error

**Comment by Mojo90** [comment]
@derek1988ec Not really. I only get this Error if sth with my cordova html/javascript-Code is wrong. Maybe there is an error? Didn't had a look what happens if a local notification is sent. And I assume that I didn't changed the code of sending local notification for this Plugin. What I could imagine that there is an Error regarding Swift 2 that it adds sth. weird or so...

**Comment by derek1988ec** [comment]
@Mojo90 yea I thought the same thing too. And usually for syntax error, most of the case that the compiler will catch it and/or error will be thrown when the app launches for the first time. That's why I find it weird that it only thrown this kind of error when I tap on the notification from the notification drawer...

**Comment by Mojo90** [comment]
What do you mean by notification drawer? Do you mean Notification Center?
But nevertheless currently I have little time to investigate this, sorry :-( we are in development of new App-Version and in preparation for Web Summit from 2.-5.11. in Dublin...

**Comment by derek1988ec** [comment]
yea apology @Mojo90, it's the notification center. I always get it messed up between android and ios. Anyway I do apologize to disturb you for your busy time. I'm looking into the problem now and will update here if I find any solution to it

**Comment by tsubik** [comment]
Notifications work for me. However, I am testing on simulator iPhone 6, iOS 9.0.

**Comment by derek1988ec** [comment]
@Mojo90 @tsubik I found the error, it's from this line of code in geofenceplugin.swift

let js = "setTimeout(\'geofence.onNotificationClicked("+ data +")\',0)"

the 'data' output 'ErrorDomain' as 'Error Domain'. Not sure why.

**Comment by garrettlangley** [comment]
@derek1988ec did you fix this?

**Comment by freinbichler** [comment]
I can now confirm that notifications are working, the problem was that I was not asked for permission to display notifications. Deleting and installing a fresh build fixed it.

**Comment by tsubik** [comment]
Please feel reopen if problem is not solved.
